package protos;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BuddyInfo.proto

public final class BuddyInfoOuterClass {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_BuddyInfo_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_BuddyInfo_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\017BuddyInfo.proto\"P\n\tBuddyInfo\022\014\n\004name\030\001" +
                        " \001(\t\022\023\n\013homeAddress\030\002 \001(\t\022\023\n\013phoneNumber" +
                        "\030\003 \001(\t\022\013\n\003age\030\004 \001(\005b\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_BuddyInfo_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_BuddyInfo_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_BuddyInfo_descriptor,
                new String[]{"Name", "HomeAddress", "PhoneNumber", "Age",});
    }

    private BuddyInfoOuterClass() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface BuddyInfoOrBuilder extends
            // @@protoc_insertion_point(interface_extends:BuddyInfo)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string name = 1;</code>
         *
         * @return The name.
         */
        String getName();

        /**
         * <code>string name = 1;</code>
         *
         * @return The bytes for name.
         */
        com.google.protobuf.ByteString
        getNameBytes();

        /**
         * <code>string homeAddress = 2;</code>
         *
         * @return The homeAddress.
         */
        String getHomeAddress();

        /**
         * <code>string homeAddress = 2;</code>
         *
         * @return The bytes for homeAddress.
         */
        com.google.protobuf.ByteString
        getHomeAddressBytes();

        /**
         * <code>string phoneNumber = 3;</code>
         *
         * @return The phoneNumber.
         */
        String getPhoneNumber();

        /**
         * <code>string phoneNumber = 3;</code>
         *
         * @return The bytes for phoneNumber.
         */
        com.google.protobuf.ByteString
        getPhoneNumberBytes();

        /**
         * <code>int32 age = 4;</code>
         *
         * @return The age.
         */
        int getAge();
    }

    /**
     * Protobuf type {@code BuddyInfo}
     */
    public static final class BuddyInfo extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:BuddyInfo)
            BuddyInfoOrBuilder {
        public static final int NAME_FIELD_NUMBER = 1;
        public static final int HOMEADDRESS_FIELD_NUMBER = 2;
        public static final int PHONENUMBER_FIELD_NUMBER = 3;
        public static final int AGE_FIELD_NUMBER = 4;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:BuddyInfo)
        private static final BuddyInfo DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<BuddyInfo>
                PARSER = new com.google.protobuf.AbstractParser<BuddyInfo>() {
            @Override
            public BuddyInfo parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new BuddyInfo(input, extensionRegistry);
            }
        };

        static {
            DEFAULT_INSTANCE = new BuddyInfo();
        }

        private volatile Object name_;
        private volatile Object homeAddress_;
        private volatile Object phoneNumber_;
        private int age_;
        private byte memoizedIsInitialized = -1;

        // Use BuddyInfo.newBuilder() to construct.
        private BuddyInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private BuddyInfo() {
            name_ = "";
            homeAddress_ = "";
            phoneNumber_ = "";
        }

        private BuddyInfo(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            String s = input.readStringRequireUtf8();

                            name_ = s;
                            break;
                        }
                        case 18: {
                            String s = input.readStringRequireUtf8();

                            homeAddress_ = s;
                            break;
                        }
                        case 26: {
                            String s = input.readStringRequireUtf8();

                            phoneNumber_ = s;
                            break;
                        }
                        case 32: {

                            age_ = input.readInt32();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return BuddyInfoOuterClass.internal_static_BuddyInfo_descriptor;
        }

        public static BuddyInfo parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static BuddyInfo parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static BuddyInfo parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static BuddyInfo parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static BuddyInfo parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static BuddyInfo parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static BuddyInfo parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static BuddyInfo parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static BuddyInfo parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static BuddyInfo parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static BuddyInfo parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static BuddyInfo parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(BuddyInfo prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static BuddyInfo getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<BuddyInfo> parser() {
            return PARSER;
        }

        @Override
        @SuppressWarnings({"unused"})
        protected Object newInstance(
                UnusedPrivateParameter unused) {
            return new BuddyInfo();
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return BuddyInfoOuterClass.internal_static_BuddyInfo_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            BuddyInfo.class, Builder.class);
        }

        /**
         * <code>string name = 1;</code>
         *
         * @return The name.
         */
        public String getName() {
            Object ref = name_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                name_ = s;
                return s;
            }
        }

        /**
         * <code>string name = 1;</code>
         *
         * @return The bytes for name.
         */
        public com.google.protobuf.ByteString
        getNameBytes() {
            Object ref = name_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string homeAddress = 2;</code>
         *
         * @return The homeAddress.
         */
        public String getHomeAddress() {
            Object ref = homeAddress_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                homeAddress_ = s;
                return s;
            }
        }

        /**
         * <code>string homeAddress = 2;</code>
         *
         * @return The bytes for homeAddress.
         */
        public com.google.protobuf.ByteString
        getHomeAddressBytes() {
            Object ref = homeAddress_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                homeAddress_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string phoneNumber = 3;</code>
         *
         * @return The phoneNumber.
         */
        public String getPhoneNumber() {
            Object ref = phoneNumber_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                phoneNumber_ = s;
                return s;
            }
        }

        /**
         * <code>string phoneNumber = 3;</code>
         *
         * @return The bytes for phoneNumber.
         */
        public com.google.protobuf.ByteString
        getPhoneNumberBytes() {
            Object ref = phoneNumber_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                phoneNumber_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>int32 age = 4;</code>
         *
         * @return The age.
         */
        public int getAge() {
            return age_;
        }

        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getNameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
            }
            if (!getHomeAddressBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, homeAddress_);
            }
            if (!getPhoneNumberBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, phoneNumber_);
            }
            if (age_ != 0) {
                output.writeInt32(4, age_);
            }
            unknownFields.writeTo(output);
        }

        @Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getNameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
            }
            if (!getHomeAddressBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, homeAddress_);
            }
            if (!getPhoneNumberBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, phoneNumber_);
            }
            if (age_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(4, age_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof BuddyInfo)) {
                return super.equals(obj);
            }
            BuddyInfo other = (BuddyInfo) obj;

            if (!getName()
                    .equals(other.getName())) return false;
            if (!getHomeAddress()
                    .equals(other.getHomeAddress())) return false;
            if (!getPhoneNumber()
                    .equals(other.getPhoneNumber())) return false;
            if (getAge()
                    != other.getAge()) return false;
            return unknownFields.equals(other.unknownFields);
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + NAME_FIELD_NUMBER;
            hash = (53 * hash) + getName().hashCode();
            hash = (37 * hash) + HOMEADDRESS_FIELD_NUMBER;
            hash = (53 * hash) + getHomeAddress().hashCode();
            hash = (37 * hash) + PHONENUMBER_FIELD_NUMBER;
            hash = (53 * hash) + getPhoneNumber().hashCode();
            hash = (37 * hash) + AGE_FIELD_NUMBER;
            hash = (53 * hash) + getAge();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        @Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @Override
        public com.google.protobuf.Parser<BuddyInfo> getParserForType() {
            return PARSER;
        }

        @Override
        public BuddyInfo getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code BuddyInfo}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:BuddyInfo)
                BuddyInfoOrBuilder {
            private Object name_ = "";
            private Object homeAddress_ = "";
            private Object phoneNumber_ = "";
            private int age_;

            // Construct using BuddyInfoOuterClass.BuddyInfo.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return BuddyInfoOuterClass.internal_static_BuddyInfo_descriptor;
            }

            @Override
            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return BuddyInfoOuterClass.internal_static_BuddyInfo_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                BuddyInfo.class, Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @Override
            public Builder clear() {
                super.clear();
                name_ = "";

                homeAddress_ = "";

                phoneNumber_ = "";

                age_ = 0;

                return this;
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return BuddyInfoOuterClass.internal_static_BuddyInfo_descriptor;
            }

            @Override
            public BuddyInfo getDefaultInstanceForType() {
                return BuddyInfo.getDefaultInstance();
            }

            @Override
            public BuddyInfo build() {
                BuddyInfo result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public BuddyInfo buildPartial() {
                BuddyInfo result = new BuddyInfo(this);
                result.name_ = name_;
                result.homeAddress_ = homeAddress_;
                result.phoneNumber_ = phoneNumber_;
                result.age_ = age_;
                onBuilt();
                return result;
            }

            @Override
            public Builder clone() {
                return super.clone();
            }

            @Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return super.setField(field, value);
            }

            @Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return super.addRepeatedField(field, value);
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof BuddyInfo) {
                    return mergeFrom((BuddyInfo) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(BuddyInfo other) {
                if (other == BuddyInfo.getDefaultInstance()) return this;
                if (!other.getName().isEmpty()) {
                    name_ = other.name_;
                    onChanged();
                }
                if (!other.getHomeAddress().isEmpty()) {
                    homeAddress_ = other.homeAddress_;
                    onChanged();
                }
                if (!other.getPhoneNumber().isEmpty()) {
                    phoneNumber_ = other.phoneNumber_;
                    onChanged();
                }
                if (other.getAge() != 0) {
                    setAge(other.getAge());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @Override
            public final boolean isInitialized() {
                return true;
            }

            @Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                BuddyInfo parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (BuddyInfo) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>string name = 1;</code>
             *
             * @return The name.
             */
            public String getName() {
                Object ref = name_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    name_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string name = 1;</code>
             *
             * @param value The name to set.
             * @return This builder for chaining.
             */
            public Builder setName(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                name_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string name = 1;</code>
             *
             * @return The bytes for name.
             */
            public com.google.protobuf.ByteString
            getNameBytes() {
                Object ref = name_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    name_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string name = 1;</code>
             *
             * @param value The bytes for name to set.
             * @return This builder for chaining.
             */
            public Builder setNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                name_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string name = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearName() {

                name_ = getDefaultInstance().getName();
                onChanged();
                return this;
            }

            /**
             * <code>string homeAddress = 2;</code>
             *
             * @return The homeAddress.
             */
            public String getHomeAddress() {
                Object ref = homeAddress_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    homeAddress_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string homeAddress = 2;</code>
             *
             * @param value The homeAddress to set.
             * @return This builder for chaining.
             */
            public Builder setHomeAddress(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                homeAddress_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string homeAddress = 2;</code>
             *
             * @return The bytes for homeAddress.
             */
            public com.google.protobuf.ByteString
            getHomeAddressBytes() {
                Object ref = homeAddress_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    homeAddress_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string homeAddress = 2;</code>
             *
             * @param value The bytes for homeAddress to set.
             * @return This builder for chaining.
             */
            public Builder setHomeAddressBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                homeAddress_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string homeAddress = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearHomeAddress() {

                homeAddress_ = getDefaultInstance().getHomeAddress();
                onChanged();
                return this;
            }

            /**
             * <code>string phoneNumber = 3;</code>
             *
             * @return The phoneNumber.
             */
            public String getPhoneNumber() {
                Object ref = phoneNumber_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    phoneNumber_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string phoneNumber = 3;</code>
             *
             * @param value The phoneNumber to set.
             * @return This builder for chaining.
             */
            public Builder setPhoneNumber(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                phoneNumber_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string phoneNumber = 3;</code>
             *
             * @return The bytes for phoneNumber.
             */
            public com.google.protobuf.ByteString
            getPhoneNumberBytes() {
                Object ref = phoneNumber_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    phoneNumber_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string phoneNumber = 3;</code>
             *
             * @param value The bytes for phoneNumber to set.
             * @return This builder for chaining.
             */
            public Builder setPhoneNumberBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                phoneNumber_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string phoneNumber = 3;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearPhoneNumber() {

                phoneNumber_ = getDefaultInstance().getPhoneNumber();
                onChanged();
                return this;
            }

            /**
             * <code>int32 age = 4;</code>
             *
             * @return The age.
             */
            public int getAge() {
                return age_;
            }

            /**
             * <code>int32 age = 4;</code>
             *
             * @param value The age to set.
             * @return This builder for chaining.
             */
            public Builder setAge(int value) {

                age_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 age = 4;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearAge() {

                age_ = 0;
                onChanged();
                return this;
            }

            @Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:BuddyInfo)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
